ETL_STATUS <- "DEV"
SQL_SERVER <- if (ETL_STATUS == "PROD") {
  "dynamo.idir.bcgov\\CA_PRD"
} else {
  "windfarm.idir.bcgov\\CA_TST"
}
DB_NAME <- "BuildingIntelligence"
SCHEMA_NAME <- "CbreStaging"
TABLE_NAME <- "pjm_dim_project"
CBRE_TABLE_NAME <- "pjm_dim_project_vw"

# Load libraries
library(assertthat, quietly = TRUE, warn.conflicts = FALSE)
library(base64enc, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(here, quietly = TRUE, warn.conflicts = FALSE)
library(httr2, quietly = TRUE, warn.conflicts = FALSE)
library(jsonlite, quietly = TRUE, warn.conflicts = FALSE)
library(lubridate, quietly = TRUE, warn.conflicts = FALSE)
library(purrr, quietly = TRUE, warn.conflicts = FALSE)
library(tibble, quietly = TRUE, warn.conflicts = FALSE)
library(tidyr, quietly = TRUE, warn.conflicts = FALSE)

library(odbc, quietly = TRUE, warn.conflicts = FALSE)
library(DBI, quietly = TRUE, warn.conflicts = FALSE)

# Load helper functions
source(here::here("./utilities/R/cbre_api_function.R"))
source(here::here("./utilities/R/event_logger.R"))
source(here::here("./utilities/R/sql_helper_functions.R"))

# Connect to SQL database
con <- dbConnect(
  odbc(),
  driver = "ODBC Driver 17 for SQL Server",
  server = SQL_SERVER,
  database = DB_NAME,
  Trusted_Connection = "Yes"
)

target_table <- Id(schema = SCHEMA_NAME, table = TABLE_NAME)
temp_table <- paste0("#", TABLE_NAME, "Temp")

raw_data <- extract_cbre_data(CBRE_TABLE_NAME)

cleaned_data <- raw_data |>
  select_if(~ !all(is.na(.))) |>
  select_if(~ !all(. == 0)) |>
  select_if(~ !all(. == '-1')) |>
  select_if(~ !all(. == "N/A")) |>
  select_if(~ !all(. == "-")) |>
  mutate(RefreshDate = as.POSIXct(Sys.Date())) |>
  select(
    RefreshDate,
    project_skey,
    project_number,
    project_id,
    csf_ytdworkcomplete,
    csf_wsiregion,
    csf_workcomplete,
    csf_transaction_flag,
    csf_totalforecastfinalcost,
    csf_servicetype,
    csf_proposeduseagreement,
    csf_projecttype,
    csf_projectsubtype,
    csf_programtype,
    csf_prevcurrfyytdvowcomp = csf_previouslyreportedcurrentfyytdvowcomplete,
    csf_pmosource,
    csf_pjmfeepercentage,
    csf_partitionid,
    csf_modifieddatetime,
    csf_ministryparentorg,
    csf_migratedprojectid,
    csf_leaseid,
    csf_identifiedproject,
    csf_id,
    csf_fundingtype,
    csf_fundingsource,
    csf_estimatetype,
    csf_domainpartitionid,
    csf_createddatetime,
    csf_complexity,
    csf_clientrecoverable,
    csf_chargeaction,
    csf_branchchildorg,
    csf_aresnumber,
    csf_agreementnumber,
    charter_approved_offline_f,
    byp_online_client_apprv_f = bypass_online_client_approval_f,
    int_engagement_letter_ex_f = internal_engagement_letter_executed_f,
    risks_assumpt_constraints = risks_assumptions_constraints,
    is_active,
    client_project_status,
    source_client_name,
    source_created_ts,
    source_unique_id,
    source_partition_id,
    project_created_date,
    sub_industry_type,
    risk_status,
    schedule_health,
    budget_health,
    overall_project_health,
    client_industry,
    client_project_number,
    cbre_organization,
    cbre_operating_model,
    project_comment,
    project_type,
    project_currency,
    scope_desc,
    project_number,
    project_name,
    delivery_account,
    project_quality,
    proj_mngmnt_deliverables = project_management_deliverables,
    project_decision_framework,
    communications,
    core_project_team,
    project_schedule,
    project_budget,
    project_scope,
    project_objective,
    standard_project_type,
    qualify_for_fusion_f,
    fusion_dir_response_status = fusion_director_response_status,
    fusion_project_type,
    risk_comments,
    schedule_comments,
    budget_comments,
    csf_scopehealthcomments,
    csf_projadminnotes = csf_projectadministrationnotes,
    csf_rpdlaborrecoverypercent,
    csf_scopehealth,
    csf_clientbillingstatus,
    record_type,
    fusion_enabled_f,
    csf_fyclosed,
    csf_capplanningreference = csf_capitalplanningreference,
    csf_revenuerecovery,
    csf_accountingnotes,
    csf_psrapplicable,
    csf_erprojectcategory,
    csf_parentprojectnumber
  )

# dbRemoveTable(con, target_table)

if (!dbExistsTable(con, target_table)) {
  sql <- paste0(
    "CREATE TABLE ",
    SCHEMA_NAME,
    ".",
    TABLE_NAME,
    " (
      RefreshDate                 DATETIME2(3)   NOT NULL,
      project_skey                INT            NOT NULL,
      project_number              NVARCHAR(20),
      project_id                  INT,
      csf_ytdworkcomplete         NVARCHAR(30),
      csf_wsiregion               NVARCHAR(60),
      csf_workcomplete            NVARCHAR(30),
      csf_transaction_flag        NVARCHAR(5),
      csf_totalforecastfinalcost  NVARCHAR(30),
      csf_source_system           NVARCHAR(15),
      csf_servicetype             NVARCHAR(60),
      csf_proposeduseagreement    NVARCHAR(15),
      csf_projecttype             NVARCHAR(30),
      csf_projectsubtype          NVARCHAR(20),
      csf_programtype             NVARCHAR(60),
      csf_prevcurrfyytdvowcomp    NVARCHAR(30),
      csf_pmosource               NVARCHAR(30),
      csf_pjmfeepercentage        NVARCHAR(10),
      csf_partitionid             INT,
      csf_modifieddatetime        NVARCHAR(30),
      csf_ministryparentorg       NVARCHAR(90),
      csf_migratedprojectid       NVARCHAR(140),
      csf_leaseid                 NVARCHAR(40),
      csf_identifiedproject       BIT,
      csf_id                      INT,
      csf_fundingtype             NVARCHAR(25),
      csf_fundingsource           NVARCHAR(15),
      csf_estimatetype            NVARCHAR(20),
      csf_domainpartitionid       INT,
      csf_createddatetime         NVARCHAR(30),
      csf_complexity              NVARCHAR(25),
      csf_clientrecoverable       BIT,
      csf_chargeaction            NVARCHAR(10),
      csf_branchchildorg          NVARCHAR(80),
      csf_aresnumber              NVARCHAR(40),
      csf_agreementnumber         NVARCHAR(75),
      charter_approved_offline_f  NVARCHAR(1),
      byp_online_client_apprv_f   NVARCHAR(1),
      int_engagement_letter_ex_f  NVARCHAR(1),
      risks_assumpt_constraints   NVARCHAR(1000),
      is_active                   NVARCHAR(1),
      client_project_status       NVARCHAR(90),
      source_client_name          NVARCHAR(25),
      source_created_ts           NVARCHAR(30),
      source_unique_id            NVARCHAR(20),
      source_partition_id         INT,
      project_created_date        NVARCHAR(30),
      sub_industry_type           NVARCHAR(60),
      risk_status                 NVARCHAR(15),
      schedule_health             NVARCHAR(15),
      budget_health               NVARCHAR(15),
      overall_project_health      NVARCHAR(15),
      client_industry             NVARCHAR(40),
      client_project_number       NVARCHAR(30),
      cbre_organization           NVARCHAR(20),
      cbre_operating_model        NVARCHAR(20),
      project_comment             NVARCHAR(MAX),
      project_type                NVARCHAR(30),
      project_currency            NVARCHAR(10),
      scope_desc                  NVARCHAR(MAX),
      project_name                NVARCHAR(200),
      delivery_account            NVARCHAR(80),
      project_quality             NVARCHAR(200),
      proj_mngmnt_deliverables    NVARCHAR(250),
      project_decision_framework  NVARCHAR(220),
      communications              NVARCHAR(450),
      core_project_team           NVARCHAR(3000),
      project_schedule            NVARCHAR(600),
      project_budget              NVARCHAR(600),
      project_scope               NVARCHAR(MAX),
      project_objective           NVARCHAR(1500),
      standard_project_type       NVARCHAR(50),
      qualify_for_fusion_f        NVARCHAR(1),
      fusion_dir_response_status  NVARCHAR(25),
      fusion_project_type         NVARCHAR(50),
      risk_comments               NVARCHAR(1600),
      schedule_comments           NVARCHAR(1600),
      budget_comments             NVARCHAR(2200),
      csf_scopehealthcomments     NVARCHAR(1500),
      csf_projadminnotes          NVARCHAR(2000),
      csf_rpdlaborrecoverypercent NVARCHAR(30),
      csf_scopehealth             NVARCHAR(15),
      csf_clientbillingstatus     NVARCHAR(40),
      record_type                 NVARCHAR(15),
      fusion_enabled_f            NVARCHAR(2),
      csf_fyclosed                NVARCHAR(15),
      csf_capplanningreference    NVARCHAR(700),
      csf_revenuerecovery         BIT,
      csf_accountingnotes         NVARCHAR(40),
      csf_psrapplicable           NVARCHAR(10),
      csf_erprojectcategory       NVARCHAR(50),
      csf_parentprojectnumber     NVARCHAR(30)
    );"
  )

  dbExecute(con, sql)
}

# Database Transaction ####
# Control database transaction to ensure all steps done together or not at all
dbBegin(con)

tryCatch(
  {
    if (dbExistsTable(con, temp_table)) {
      dbRemoveTable(con, temp_table)
    }

    dbExecute(
      con,
      paste0(
        "CREATE TABLE ",
        temp_table,
        " (
        RefreshDate                 DATETIME2(3)   NOT NULL,
        project_skey                INT            NOT NULL,
        project_number              NVARCHAR(20),
        project_id                  INT,
        csf_ytdworkcomplete         NVARCHAR(30),
        csf_wsiregion               NVARCHAR(60),
        csf_workcomplete            NVARCHAR(30),
        csf_transaction_flag        NVARCHAR(5),
        csf_totalforecastfinalcost  NVARCHAR(30),
        csf_source_system           NVARCHAR(15),
        csf_servicetype             NVARCHAR(60),
        csf_proposeduseagreement    NVARCHAR(15),
        csf_projecttype             NVARCHAR(30),
        csf_projectsubtype          NVARCHAR(20),
        csf_programtype             NVARCHAR(60),
        csf_prevcurrfyytdvowcomp    NVARCHAR(30),
        csf_pmosource               NVARCHAR(30),
        csf_pjmfeepercentage        NVARCHAR(10),
        csf_partitionid             INT,
        csf_modifieddatetime        NVARCHAR(30),
        csf_ministryparentorg       NVARCHAR(90),
        csf_migratedprojectid       NVARCHAR(140),
        csf_leaseid                 NVARCHAR(40),
        csf_identifiedproject       BIT,
        csf_id                      INT,
        csf_fundingtype             NVARCHAR(25),
        csf_fundingsource           NVARCHAR(15),
        csf_estimatetype            NVARCHAR(20),
        csf_domainpartitionid       INT,
        csf_createddatetime         NVARCHAR(30),
        csf_complexity              NVARCHAR(25),
        csf_clientrecoverable       BIT,
        csf_chargeaction            NVARCHAR(10),
        csf_branchchildorg          NVARCHAR(80),
        csf_aresnumber              NVARCHAR(40),
        csf_agreementnumber         NVARCHAR(75),
        charter_approved_offline_f  NVARCHAR(1),
        byp_online_client_apprv_f   NVARCHAR(1),
        int_engagement_letter_ex_f  NVARCHAR(1),
        risks_assumpt_constraints   NVARCHAR(1000),
        is_active                   NVARCHAR(1),
        client_project_status       NVARCHAR(90),
        source_client_name          NVARCHAR(25),
        source_created_ts           NVARCHAR(30),
        source_unique_id            NVARCHAR(20),
        source_partition_id         INT,
        project_created_date        NVARCHAR(30),
        sub_industry_type           NVARCHAR(60),
        risk_status                 NVARCHAR(15),
        schedule_health             NVARCHAR(15),
        budget_health               NVARCHAR(15),
        overall_project_health      NVARCHAR(15),
        client_industry             NVARCHAR(40),
        client_project_number       NVARCHAR(30),
        cbre_organization           NVARCHAR(20),
        cbre_operating_model        NVARCHAR(20),
        project_comment             NVARCHAR(MAX),
        project_type                NVARCHAR(30),
        project_currency            NVARCHAR(10),
        scope_desc                  NVARCHAR(MAX),
        project_name                NVARCHAR(200),
        delivery_account            NVARCHAR(80),
        project_quality             NVARCHAR(200),
        proj_mngmnt_deliverables    NVARCHAR(250),
        project_decision_framework  NVARCHAR(220),
        communications              NVARCHAR(450),
        core_project_team           NVARCHAR(3000),
        project_schedule            NVARCHAR(600),
        project_budget              NVARCHAR(600),
        project_scope               NVARCHAR(MAX),
        project_objective           NVARCHAR(1500),
        standard_project_type       NVARCHAR(50),
        qualify_for_fusion_f        NVARCHAR(1),
        fusion_dir_response_status  NVARCHAR(25),
        fusion_project_type         NVARCHAR(50),
        risk_comments               NVARCHAR(1600),
        schedule_comments           NVARCHAR(1600),
        budget_comments             NVARCHAR(2200),
        csf_scopehealthcomments     NVARCHAR(1500),
        csf_projadminnotes          NVARCHAR(2000),
        csf_rpdlaborrecoverypercent NVARCHAR(30),
        csf_scopehealth             NVARCHAR(15),
        csf_clientbillingstatus     NVARCHAR(40),
        record_type                 NVARCHAR(15),
        fusion_enabled_f            NVARCHAR(2),
        csf_fyclosed                NVARCHAR(15),
        csf_capplanningreference    NVARCHAR(700),
        csf_revenuerecovery         BIT,
        csf_accountingnotes         NVARCHAR(40),
        csf_psrapplicable           NVARCHAR(10),
        csf_erprojectcategory       NVARCHAR(50),
        csf_parentprojectnumber     NVARCHAR(30)
      );"
      )
    )

    dbWriteTable(
      con,
      name = temp_table,
      value = cleaned_data,
      append = TRUE,
      overwrite = FALSE
    )

    # Update existing rows in the target table that have changed

    n_updated <- dbExecute(
      con,
      paste0(
        "
    UPDATE tgt
      SET
        tgt.RefreshDate                 = src.RefreshDate,
        tgt.project_number              = src.project_number,
        tgt.project_id                  = src.project_id,
        tgt.csf_ytdworkcomplete         = src.csf_ytdworkcomplete,
        tgt.csf_wsiregion               = src.csf_wsiregion,
        tgt.csf_workcomplete            = src.csf_workcomplete,
        tgt.csf_transaction_flag        = src.csf_transaction_flag,
        tgt.csf_totalforecastfinalcost  = src.csf_totalforecastfinalcost,
        tgt.csf_source_system           = src.csf_source_system,
        tgt.csf_servicetype             = src.csf_servicetype,
        tgt.csf_proposeduseagreement    = src.csf_proposeduseagreement,
        tgt.csf_projecttype             = src.csf_projecttype,
        tgt.csf_projectsubtype          = src.csf_projectsubtype,
        tgt.csf_programtype             = src.csf_programtype,
        tgt.csf_prevcurrfyytdvowcomp    = src.csf_prevcurrfyytdvowcomp,
        tgt.csf_pmosource               = src.csf_pmosource,
        tgt.csf_pjmfeepercentage        = src.csf_pjmfeepercentage,
        tgt.csf_partitionid             = src.csf_partitionid,
        tgt.csf_modifieddatetime        = src.csf_modifieddatetime,
        tgt.csf_ministryparentorg       = src.csf_ministryparentorg,
        tgt.csf_migratedprojectid       = src.csf_migratedprojectid,
        tgt.csf_leaseid                 = src.csf_leaseid,
        tgt.csf_identifiedproject       = src.csf_identifiedproject,
        tgt.csf_id                      = src.csf_id,
        tgt.csf_fundingtype             = src.csf_fundingtype,
        tgt.csf_fundingsource           = src.csf_fundingsource,
        tgt.csf_estimatetype            = src.csf_estimatetype,
        tgt.csf_domainpartitionid       = src.csf_domainpartitionid,
        tgt.csf_createddatetime         = src.csf_createddatetime,
        tgt.csf_complexity              = src.csf_complexity,
        tgt.csf_clientrecoverable       = src.csf_clientrecoverable,
        tgt.csf_chargeaction            = src.csf_chargeaction,
        tgt.csf_branchchildorg          = src.csf_branchchildorg,
        tgt.csf_aresnumber              = src.csf_aresnumber,
        tgt.csf_agreementnumber         = src.csf_agreementnumber,
        tgt.charter_approved_offline_f  = src.charter_approved_offline_f,
        tgt.byp_online_client_apprv_f   = src.byp_online_client_apprv_f,
        tgt.int_engagement_letter_ex_f  = src.int_engagement_letter_ex_f,
        tgt.risks_assumpt_constraints   = src.risks_assumpt_constraints,
        tgt.is_active                   = src.is_active,
        tgt.client_project_status       = src.client_project_status,
        tgt.source_client_name          = src.source_client_name,
        tgt.source_created_ts           = src.source_created_ts,
        tgt.source_unique_id            = src.source_unique_id,
        tgt.source_partition_id         = src.source_partition_id,
        tgt.project_created_date        = src.project_created_date,
        tgt.sub_industry_type            = src.sub_industry_type,
        tgt.risk_status                 = src.risk_status,
        tgt.schedule_health             = src.schedule_health,
        tgt.budget_health               = src.budget_health,
        tgt.overall_project_health      = src.overall_project_health,
        tgt.client_industry             = src.client_industry,
        tgt.client_project_number       = src.client_project_number,
        tgt.cbre_organization           = src.cbre_organization,
        tgt.cbre_operating_model        = src.cbre_operating_model,
        tgt.project_comment             = src.project_comment,
        tgt.project_type                = src.project_type,
        tgt.project_currency            = src.project_currency,
        tgt.scope_desc                  = src.scope_desc,
        tgt.project_name                = src.project_name,
        tgt.delivery_account            = src.delivery_account,
        tgt.project_quality             = src.project_quality,
        tgt.proj_mngmnt_deliverables    = src.proj_mngmnt_deliverables,
        tgt.project_decision_framework  = src.project_decision_framework,
        tgt.communications              = src.communications,
        tgt.core_project_team           = src.core_project_team,
        tgt.project_schedule            = src.project_schedule,
        tgt.project_budget              = src.project_budget,
        tgt.project_scope               = src.project_scope,
        tgt.project_objective           = src.project_objective,
        tgt.standard_project_type       = src.standard_project_type,
        tgt.qualify_for_fusion_f        = src.qualify_for_fusion_f,
        tgt.fusion_dir_response_status  = src.fusion_dir_response_status,
        tgt.fusion_project_type         = src.fusion_project_type,
        tgt.risk_comments               = src.risk_comments,
        tgt.schedule_comments           = src.schedule_comments,
        tgt.budget_comments             = src.budget_comments,
        tgt.csf_scopehealthcomments     = src.csf_scopehealthcomments,
        tgt.csf_projadminnotes          = src.csf_projadminnotes,
        tgt.csf_rpdlaborrecoverypercent = src.csf_rpdlaborrecoverypercent,
        tgt.csf_scopehealth             = src.csf_scopehealth,
        tgt.csf_clientbillingstatus     = src.csf_clientbillingstatus,
        tgt.record_type                 = src.record_type,
        tgt.fusion_enabled_f            = src.fusion_enabled_f,
        tgt.csf_fyclosed                = src.csf_fyclosed,
        tgt.csf_capplanningreference    = src.csf_capplanningreference,
        tgt.csf_revenuerecovery         = src.csf_revenuerecovery,
        tgt.csf_accountingnotes         = src.csf_accountingnotes,
        tgt.csf_psrapplicable           = src.csf_psrapplicable,
        tgt.csf_erprojectcategory       = src.csf_erprojectcategory,
        tgt.csf_parentprojectnumber     = src.csf_parentprojectnumber
      FROM ",
        SCHEMA_NAME,
        ".",
        TABLE_NAME,
        " tgt
      JOIN ",
        temp_table,
        " src
        ON tgt.project_skey = src.project_skey;
      "
      )
    )

    # Insert new rows that don't exist in the SQL table
    n_inserted <- dbExecute(
      con,
      paste0(
        "
    INSERT INTO ",
        SCHEMA_NAME,
        ".",
        TABLE_NAME,
        " (
      RefreshDate,
      project_skey,
      project_number,
      project_id,
      csf_ytdworkcomplete,
      csf_wsiregion,
      csf_workcomplete,
      csf_transaction_flag,
      csf_totalforecastfinalcost,
      csf_source_system,
      csf_servicetype,
      csf_proposeduseagreement,
      csf_projecttype,
      csf_projectsubtype,
      csf_programtype,
      csf_prevcurrfyytdvowcomp,
      csf_pmosource,
      csf_pjmfeepercentage,
      csf_partitionid,
      csf_modifieddatetime,
      csf_ministryparentorg,
      csf_migratedprojectid,
      csf_leaseid,
      csf_identifiedproject,
      csf_id,
      csf_fundingtype,
      csf_fundingsource,
      csf_estimatetype,
      csf_domainpartitionid,
      csf_createddatetime,
      csf_complexity,
      csf_clientrecoverable,
      csf_chargeaction,
      csf_branchchildorg,
      csf_aresnumber,
      csf_agreementnumber,
      charter_approved_offline_f,
      byp_online_client_apprv_f,
      int_engagement_letter_ex_f,
      risks_assumpt_constraints,
      is_active,
      client_project_status,
      source_client_name,
      source_created_ts,
      source_unique_id,
      source_partition_id,
      project_created_date,
      sub_industry_type,
      risk_status,
      schedule_health,
      budget_health,
      overall_project_health,
      client_industry,
      client_project_number,
      cbre_organization,
      cbre_operating_model,
      project_comment,
      project_type,
      project_currency,
      scope_desc,
      project_name,
      delivery_account,
      project_quality,
      proj_mngmnt_deliverables,
      project_decision_framework,
      communications,
      core_project_team,
      project_schedule,
      project_budget,
      project_scope,
      project_objective,
      standard_project_type,
      qualify_for_fusion_f,
      fusion_dir_response_status,
      fusion_project_type,
      risk_comments,
      schedule_comments,
      budget_comments,
      csf_scopehealthcomments,
      csf_projadminnotes,
      csf_rpdlaborrecoverypercent,
      csf_scopehealth,
      csf_clientbillingstatus,
      record_type,
      fusion_enabled_f,
      csf_fyclosed,
      csf_capplanningreference,
      csf_revenuerecovery,
      csf_accountingnotes,
      csf_psrapplicable,
      csf_erprojectcategory,
      csf_parentprojectnumber
    )
    SELECT
      src.RefreshDate,
      src.project_skey,
      src.project_number,
      src.project_id,
      src.csf_ytdworkcomplete,
      src.csf_wsiregion,
      src.csf_workcomplete,
      src.csf_transaction_flag,
      src.csf_totalforecastfinalcost,
      src.csf_source_system,
      src.csf_servicetype,
      src.csf_proposeduseagreement,
      src.csf_projecttype,
      src.csf_projectsubtype,
      src.csf_programtype,
      src.csf_prevcurrfyytdvowcomp,
      src.csf_pmosource,
      src.csf_pjmfeepercentage,
      src.csf_partitionid,
      src.csf_modifieddatetime,
      src.csf_ministryparentorg,
      src.csf_migratedprojectid,
      src.csf_leaseid,
      src.csf_identifiedproject,
      src.csf_id,
      src.csf_fundingtype,
      src.csf_fundingsource,
      src.csf_estimatetype,
      src.csf_domainpartitionid,
      src.csf_createddatetime,
      src.csf_complexity,
      src.csf_clientrecoverable,
      src.csf_chargeaction,
      src.csf_branchchildorg,
      src.csf_aresnumber,
      src.csf_agreementnumber,
      src.charter_approved_offline_f,
      src.byp_online_client_apprv_f,
      src.int_engagement_letter_ex_f,
      src.risks_assumpt_constraints,
      src.is_active,
      src.client_project_status,
      src.source_client_name,
      src.source_created_ts,
      src.source_unique_id,
      src.source_partition_id,
      src.project_created_date,
      src.sub_industry_type,
      src.risk_status,
      src.schedule_health,
      src.budget_health,
      src.overall_project_health,
      src.client_industry,
      src.client_project_number,
      src.cbre_organization,
      src.cbre_operating_model,
      src.project_comment,
      src.project_type,
      src.project_currency,
      src.scope_desc,
      src.project_name,
      src.delivery_account,
      src.project_quality,
      src.proj_mngmnt_deliverables,
      src.project_decision_framework,
      src.communications,
      src.core_project_team,
      src.project_schedule,
      src.project_budget,
      src.project_scope,
      src.project_objective,
      src.standard_project_type,
      src.qualify_for_fusion_f,
      src.fusion_dir_response_status,
      src.fusion_project_type,
      src.risk_comments,
      src.schedule_comments,
      src.budget_comments,
      src.csf_scopehealthcomments,
      src.csf_projadminnotes,
      src.csf_rpdlaborrecoverypercent,
      src.csf_scopehealth,
      src.csf_clientbillingstatus,
      src.record_type,
      src.fusion_enabled_f,
      src.csf_fyclosed,
      src.csf_capplanningreference,
      src.csf_revenuerecovery,
      src.csf_accountingnotes,
      src.csf_psrapplicable,
      src.csf_erprojectcategory,
      src.csf_parentprojectnumber
    FROM ",
        temp_table,
        " src
    LEFT JOIN ",
        SCHEMA_NAME,
        ".",
        TABLE_NAME,
        " tgt
      ON tgt.project_skey = src.project_skey
    WHERE tgt.project_skey IS NULL;
    "
      )
    )

    # Delete old rows that don't exist in the SQL table
    n_deleted <- dbExecute(
      con,
      paste0(
        "
      DELETE tgt
        FROM ",
        SCHEMA_NAME,
        ".",
        TABLE_NAME,
        " tgt
      LEFT JOIN ",
        temp_table,
        " src
        ON  tgt.project_skey = src.project_skey
      WHERE src.project_skey IS NULL;
        "
      )
    )

    # Complete the transaction
    dbCommit(con)

    n_inserted <<- n_inserted
    n_updated <<- n_updated
    # Rollback transaction on failure
  },
  error = function(e) {
    dbRollback(con)
    stop(e)
  }
)
